/**
 * License Key Unit Tests
 * Tests for license key generation and validation
 */

import { describe, it, expect } from 'vitest';
import {
  generateLicenseKey,
  generateUniqueLicenseKey,
  validateLicenseKeyFormat,
} from './license';

describe('generateLicenseKey', () => {
  it('should generate a key with correct format (XXXX-XXXX-XXXX-XXXX-XXXX)', () => {
    const key = generateLicenseKey();
    const segments = key.split('-');

    expect(segments).toHaveLength(5);
    segments.forEach((segment) => {
      expect(segment).toHaveLength(4);
    });
  });

  it('should only contain allowed characters (no ambiguous chars)', () => {
    const key = generateLicenseKey();
    const allowedChars = /^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789-]+$/;

    expect(key).toMatch(allowedChars);
    // Verify ambiguous characters are NOT present (0, O, I, 1)
    // Note: L is allowed in the character set
    expect(key).not.toMatch(/[0OI1]/);
  });

  it('should generate unique keys', () => {
    const keys = new Set<string>();
    for (let i = 0; i < 100; i++) {
      keys.add(generateLicenseKey());
    }
    // All 100 keys should be unique
    expect(keys.size).toBe(100);
  });

  it('should be 24 characters long (5 segments * 4 chars + 4 dashes)', () => {
    const key = generateLicenseKey();
    expect(key).toHaveLength(24);
  });
});

describe('generateUniqueLicenseKey', () => {
  it('should append timestamp to base key', async () => {
    const key = await generateUniqueLicenseKey();

    // Should have 6 segments (5 base + timestamp)
    const segments = key.split('-');
    expect(segments.length).toBeGreaterThanOrEqual(6);

    // Last segment should be a timestamp (all digits)
    const lastSegment = segments[segments.length - 1];
    expect(lastSegment).toMatch(/^\d+$/);
  });

  it('should generate unique keys even when called rapidly', async () => {
    const keys = await Promise.all([
      generateUniqueLicenseKey(),
      generateUniqueLicenseKey(),
      generateUniqueLicenseKey(),
    ]);

    const uniqueKeys = new Set(keys);
    expect(uniqueKeys.size).toBe(3);
  });
});

describe('validateLicenseKeyFormat', () => {
  it('should validate correct license key format', () => {
    expect(validateLicenseKeyFormat('ABCD-EFGH-JKLM-NPQR-STUV')).toBe(true);
    expect(validateLicenseKeyFormat('2345-6789-ABCD-EFGH-JKLM')).toBe(true);
  });

  it('should validate keys with timestamp suffix', () => {
    expect(
      validateLicenseKeyFormat('ABCD-EFGH-JKLM-NPQR-STUV-1699123456789')
    ).toBe(true);
  });

  it('should reject invalid formats', () => {
    // Too short
    expect(validateLicenseKeyFormat('ABCD-EFGH')).toBe(false);
    // Wrong segment length
    expect(validateLicenseKeyFormat('ABC-EFGH-JKLM-NPQR-STUV')).toBe(false);
    // Lowercase
    expect(validateLicenseKeyFormat('abcd-efgh-jklm-npqr-stuv')).toBe(false);
    // Invalid characters
    expect(validateLicenseKeyFormat('ABCD-EFGH-JKLM-NPQR-!!!')).toBe(false);
    // Empty string
    expect(validateLicenseKeyFormat('')).toBe(false);
  });

  it('should validate keys generated by generateLicenseKey', () => {
    const key = generateLicenseKey();
    expect(validateLicenseKeyFormat(key)).toBe(true);
  });

  it('should validate keys generated by generateUniqueLicenseKey', async () => {
    const key = await generateUniqueLicenseKey();
    expect(validateLicenseKeyFormat(key)).toBe(true);
  });
});
