/**
 * Landing Page Template with Placeholders
 * Used by build_custom_landing_page tool
 */

export const landingPageTemplate = `/**
 * {{PRODUCT_NAME}} Landing Page
 * Generated by Fabrk MCP Server
 */

'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Container } from '@/components/ui/container';
import { Card, CardContent } from '@/components/ui/card';
import {
  {{FEATURE_1_ICON}},
  {{FEATURE_2_ICON}},
  {{FEATURE_3_ICON}},
  {{FEATURE_4_ICON}},
  ChevronDown,
  Check,
  ArrowRight,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/* =============================================================================
   HERO SECTION
============================================================================= */
function HeroSection() {
  return (
    <section className="relative px-4 py-20 lg:py-32">
      <Container>
        <div className="mx-auto max-w-4xl text-center">
          <div className="mb-6 inline-block border border-border bg-muted px-4 py-1.5 text-xs">
            [{{TRUST_BADGE}}]
          </div>

          <h1 className="mb-6 text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
            {{HEADLINE}}
          </h1>

          <p className="mx-auto mb-8 max-w-2xl text-lg text-muted-foreground">
            {{DESCRIPTION}}
          </p>

          <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Button size="lg" asChild>
              <Link href="{{PRIMARY_CTA_URL}}">
                &gt; {{PRIMARY_CTA_TEXT}} <ArrowRight className="ml-2 size-4" />
              </Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="{{SECONDARY_CTA_URL}}">&gt; {{SECONDARY_CTA_TEXT}}</Link>
            </Button>
          </div>

          <div className="mt-8 flex flex-wrap items-center justify-center gap-6 text-sm text-muted-foreground">
            <span className="flex items-center gap-2">
              <Check className="size-4 text-green-500" /> {{TRUST_1}}
            </span>
            <span className="flex items-center gap-2">
              <Check className="size-4 text-green-500" /> {{TRUST_2}}
            </span>
            <span className="flex items-center gap-2">
              <Check className="size-4 text-green-500" /> {{TRUST_3}}
            </span>
          </div>
        </div>
      </Container>
    </section>
  );
}

/* =============================================================================
   PRODUCT PREVIEW SECTION
============================================================================= */
function ProductPreviewSection() {
  return (
    <section className="border-t border-border bg-muted/30 px-4 py-20 lg:py-24">
      <Container>
        <div className="mx-auto max-w-5xl">
          <div className="overflow-hidden border border-border bg-card shadow-2xl">
            <div className="flex items-center gap-2 border-b border-border bg-muted/50 px-4 py-3">
              <div className="size-3 rounded-full bg-red-500" />
              <div className="size-3 rounded-full bg-yellow-500" />
              <div className="size-3 rounded-full bg-green-500" />
              <span className="ml-4 text-xs text-muted-foreground">{{PRODUCT_URL}}</span>
            </div>
            <div className="flex aspect-video items-center justify-center bg-gradient-to-br from-muted/50 to-muted p-8">
              <div className="text-center">
                <p className="text-lg text-muted-foreground">[{{PRODUCT_NAME}} SCREENSHOT]</p>
                <p className="text-sm text-muted-foreground/70">
                  Replace this with an actual screenshot or demo video
                </p>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </section>
  );
}

/* =============================================================================
   FEATURES SECTION
============================================================================= */
function FeaturesSection() {
  const features = [
    {
      icon: {{FEATURE_1_ICON}},
      title: '{{FEATURE_1_TITLE}}',
      description: '{{FEATURE_1_DESCRIPTION}}',
    },
    {
      icon: {{FEATURE_2_ICON}},
      title: '{{FEATURE_2_TITLE}}',
      description: '{{FEATURE_2_DESCRIPTION}}',
    },
    {
      icon: {{FEATURE_3_ICON}},
      title: '{{FEATURE_3_TITLE}}',
      description: '{{FEATURE_3_DESCRIPTION}}',
    },
    {
      icon: {{FEATURE_4_ICON}},
      title: '{{FEATURE_4_TITLE}}',
      description: '{{FEATURE_4_DESCRIPTION}}',
    },
  ];

  return (
    <section className="border-t border-border px-4 py-20 lg:py-24">
      <Container>
        <div className="mx-auto mb-16 max-w-3xl text-center">
          <div className="mb-6 inline-block border border-border bg-muted px-4 py-1.5 text-xs">
            [FEATURES]
          </div>
          <h2 className="mb-6 text-3xl font-bold tracking-tight sm:text-4xl">
            {{FEATURES_HEADLINE}}
          </h2>
          <p className="text-muted-foreground">
            {{FEATURES_SUBHEADLINE}}
          </p>
        </div>

        <div className="grid gap-8 md:grid-cols-2">
          {features.map((feature) => (
            <Card key={feature.title} size="auto" className="group transition-colors hover:border-primary/50">
              <CardContent className="p-6">
                <feature.icon className="mb-4 size-10 text-primary" />
                <h3 className="mb-2 text-lg font-semibold">{feature.title}</h3>
                <p className="text-sm text-muted-foreground">{feature.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </Container>
    </section>
  );
}

/* =============================================================================
   STATS SECTION
============================================================================= */
function StatsSection() {
  const stats = [
    { value: '{{STAT_1_VALUE}}', label: '{{STAT_1_LABEL}}' },
    { value: '{{STAT_2_VALUE}}', label: '{{STAT_2_LABEL}}' },
    { value: '{{STAT_3_VALUE}}', label: '{{STAT_3_LABEL}}' },
    { value: '{{STAT_4_VALUE}}', label: '{{STAT_4_LABEL}}' },
  ];

  return (
    <section className="border-t border-border bg-muted/30 px-4 py-20 lg:py-24">
      <Container>
        <div className="grid grid-cols-2 gap-8 lg:grid-cols-4">
          {stats.map((stat) => (
            <div key={stat.label} className="text-center">
              <div className="mb-2 text-4xl font-bold">{stat.value}</div>
              <div className="text-sm text-muted-foreground">{stat.label}</div>
            </div>
          ))}
        </div>
      </Container>
    </section>
  );
}

/* =============================================================================
   HOW IT WORKS SECTION
============================================================================= */
function HowItWorksSection() {
  const steps = [
    {
      step: '01',
      title: '{{STEP_1_TITLE}}',
      description: '{{STEP_1_DESCRIPTION}}',
    },
    {
      step: '02',
      title: '{{STEP_2_TITLE}}',
      description: '{{STEP_2_DESCRIPTION}}',
    },
    {
      step: '03',
      title: '{{STEP_3_TITLE}}',
      description: '{{STEP_3_DESCRIPTION}}',
    },
  ];

  return (
    <section className="border-t border-border px-4 py-20 lg:py-24">
      <Container>
        <div className="mx-auto mb-16 max-w-3xl text-center">
          <div className="mb-6 inline-block border border-border bg-muted px-4 py-1.5 text-xs">
            [HOW IT WORKS]
          </div>
          <h2 className="mb-6 text-3xl font-bold tracking-tight sm:text-4xl">
            {{HOW_IT_WORKS_HEADLINE}}
          </h2>
          <p className="text-muted-foreground">
            {{HOW_IT_WORKS_SUBHEADLINE}}
          </p>
        </div>

        <div className="grid gap-8 md:grid-cols-3">
          {steps.map((item) => (
            <div key={item.step} className="text-center">
              <div className="mx-auto mb-4 flex size-16 items-center justify-center border border-primary text-2xl font-bold text-primary">
                {item.step}
              </div>
              <h3 className="mb-2 text-lg font-semibold">{item.title}</h3>
              <p className="text-sm text-muted-foreground">{item.description}</p>
            </div>
          ))}
        </div>
      </Container>
    </section>
  );
}

/* =============================================================================
   PRICING SECTION
============================================================================= */
function PricingSection() {
  const plans = [
    {
      name: '{{PRICE_TIER_1_NAME}}',
      price: '{{PRICE_TIER_1_PRICE}}',
      period: '{{PRICE_TIER_1_PERIOD}}',
      description: '{{PRICE_TIER_1_DESCRIPTION}}',
      features: [{{PRICE_TIER_1_FEATURES}}],
      cta: '{{PRICE_TIER_1_CTA}}',
      popular: false,
    },
    {
      name: '{{PRICE_TIER_2_NAME}}',
      price: '{{PRICE_TIER_2_PRICE}}',
      period: '{{PRICE_TIER_2_PERIOD}}',
      description: '{{PRICE_TIER_2_DESCRIPTION}}',
      features: [{{PRICE_TIER_2_FEATURES}}],
      cta: '{{PRICE_TIER_2_CTA}}',
      popular: true,
    },
    {
      name: '{{PRICE_TIER_3_NAME}}',
      price: '{{PRICE_TIER_3_PRICE}}',
      period: '{{PRICE_TIER_3_PERIOD}}',
      description: '{{PRICE_TIER_3_DESCRIPTION}}',
      features: [{{PRICE_TIER_3_FEATURES}}],
      cta: '{{PRICE_TIER_3_CTA}}',
      popular: false,
    },
  ];

  return (
    <section className="border-t border-border bg-muted/30 px-4 py-20 lg:py-24">
      <Container>
        <div className="mx-auto mb-16 max-w-3xl text-center">
          <div className="mb-6 inline-block border border-border bg-muted px-4 py-1.5 text-xs">
            [PRICING]
          </div>
          <h2 className="mb-6 text-3xl font-bold tracking-tight sm:text-4xl">
            {{PRICING_HEADLINE}}
          </h2>
          <p className="text-muted-foreground">
            {{PRICING_SUBHEADLINE}}
          </p>
        </div>

        <div className="grid gap-8 md:grid-cols-3">
          {plans.map((plan) => (
            <Card
              key={plan.name}
              size="auto"
              className={cn(
                'relative',
                plan.popular && 'border-primary border-2'
              )}
            >
              {plan.popular && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-primary px-4 py-1 text-xs text-primary-foreground">
                  MOST POPULAR
                </div>
              )}
              <CardContent className="p-6">
                <h3 className="mb-2 text-xl font-bold">{plan.name}</h3>
                <p className="mb-4 text-sm text-muted-foreground">{plan.description}</p>
                <div className="mb-6">
                  <span className="text-4xl font-bold">{plan.price}</span>
                  <span className="text-muted-foreground">{plan.period}</span>
                </div>
                <ul className="mb-8 space-y-3">
                  {plan.features.map((feature) => (
                    <li key={feature} className="flex items-center gap-2 text-sm">
                      <Check className="size-4 text-green-500" />
                      {feature}
                    </li>
                  ))}
                </ul>
                <Button
                  className="w-full"
                  variant={plan.popular ? 'default' : 'outline'}
                >
                  &gt; {plan.cta}
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </Container>
    </section>
  );
}

/* =============================================================================
   FAQ SECTION
============================================================================= */
function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqs = [
    {
      question: '{{FAQ_1_QUESTION}}',
      answer: '{{FAQ_1_ANSWER}}',
    },
    {
      question: '{{FAQ_2_QUESTION}}',
      answer: '{{FAQ_2_ANSWER}}',
    },
    {
      question: '{{FAQ_3_QUESTION}}',
      answer: '{{FAQ_3_ANSWER}}',
    },
    {
      question: '{{FAQ_4_QUESTION}}',
      answer: '{{FAQ_4_ANSWER}}',
    },
    {
      question: '{{FAQ_5_QUESTION}}',
      answer: '{{FAQ_5_ANSWER}}',
    },
  ];

  return (
    <section className="border-t border-border px-4 py-20 lg:py-24">
      <Container>
        <div className="mx-auto mb-16 max-w-3xl text-center">
          <div className="mb-6 inline-block border border-border bg-muted px-4 py-1.5 text-xs">
            [FAQ]
          </div>
          <h2 className="mb-6 text-3xl font-bold tracking-tight sm:text-4xl">
            {{FAQ_HEADLINE}}
          </h2>
          <p className="text-muted-foreground">
            {{FAQ_SUBHEADLINE}}
          </p>
        </div>

        <div className="mx-auto max-w-3xl space-y-4">
          {faqs.map((faq, index) => (
            <Card key={index} size="auto">
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="flex w-full items-center justify-between p-4 text-left transition-colors hover:bg-muted/50"
              >
                <span className="font-medium">{faq.question}</span>
                <ChevronDown
                  className={cn(
                    'size-5 text-muted-foreground transition-transform',
                    openIndex === index && 'rotate-180'
                  )}
                />
              </button>
              {openIndex === index && (
                <CardContent className="border-t border-border bg-muted/30 pt-4">
                  <p className="text-sm text-muted-foreground">{faq.answer}</p>
                </CardContent>
              )}
            </Card>
          ))}
        </div>
      </Container>
    </section>
  );
}

/* =============================================================================
   FINAL CTA SECTION
============================================================================= */
function FinalCTASection() {
  return (
    <section className="border-t border-border bg-muted/30 px-4 py-20 lg:py-24">
      <Container>
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="mb-6 text-3xl font-bold tracking-tight sm:text-4xl">
            {{FINAL_CTA_HEADLINE}}
          </h2>
          <p className="mb-8 text-lg text-muted-foreground">
            {{FINAL_CTA_DESCRIPTION}}
          </p>
          <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Button size="lg" asChild>
              <Link href="{{FINAL_CTA_PRIMARY_URL}}">
                &gt; {{FINAL_CTA_PRIMARY_TEXT}} <ArrowRight className="ml-2 size-4" />
              </Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="{{FINAL_CTA_SECONDARY_URL}}">&gt; {{FINAL_CTA_SECONDARY_TEXT}}</Link>
            </Button>
          </div>
        </div>
      </Container>
    </section>
  );
}

/* =============================================================================
   MAIN PAGE COMPONENT
============================================================================= */
export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      <HeroSection />
      <ProductPreviewSection />
      <FeaturesSection />
      <StatsSection />
      <HowItWorksSection />
      <PricingSection />
      <FAQSection />
      <FinalCTASection />
    </div>
  );
}
`;

// Default values for template
export const defaultValues: Record<string, string> = {
  PRODUCT_NAME: 'MyProduct',
  PRODUCT_URL: 'myproduct.com',
  TRUST_BADGE: 'TRUSTED BY 1,000+ USERS',
  HEADLINE: 'YOUR PRODUCT HEADLINE GOES HERE',
  DESCRIPTION: 'A clear, compelling description of what your product does and why it matters.',
  PRIMARY_CTA_TEXT: 'GET STARTED FREE',
  PRIMARY_CTA_URL: '/signup',
  SECONDARY_CTA_TEXT: 'WATCH DEMO',
  SECONDARY_CTA_URL: '/demo',
  TRUST_1: 'No credit card required',
  TRUST_2: '14-day free trial',
  TRUST_3: 'Cancel anytime',

  // Features
  FEATURES_HEADLINE: 'EVERYTHING YOU NEED TO SUCCEED',
  FEATURES_SUBHEADLINE: "We've built the features you need so you can focus on what matters most.",
  FEATURE_1_ICON: 'Zap',
  FEATURE_1_TITLE: 'LIGHTNING FAST',
  FEATURE_1_DESCRIPTION: 'Built for speed. Your users will notice the difference immediately.',
  FEATURE_2_ICON: 'Shield',
  FEATURE_2_TITLE: 'SECURE BY DEFAULT',
  FEATURE_2_DESCRIPTION: 'Enterprise-grade security out of the box. Sleep well at night.',
  FEATURE_3_ICON: 'Globe',
  FEATURE_3_TITLE: 'WORKS EVERYWHERE',
  FEATURE_3_DESCRIPTION: 'Deploy anywhere. Works on all devices and browsers.',
  FEATURE_4_ICON: 'BarChart3',
  FEATURE_4_TITLE: 'POWERFUL ANALYTICS',
  FEATURE_4_DESCRIPTION: 'Know exactly how your product is performing at all times.',

  // Stats
  STAT_1_VALUE: '10,000+',
  STAT_1_LABEL: 'Active Users',
  STAT_2_VALUE: '4.9/5',
  STAT_2_LABEL: 'User Rating',
  STAT_3_VALUE: '99.9%',
  STAT_3_LABEL: 'Uptime',
  STAT_4_VALUE: '50+',
  STAT_4_LABEL: 'Countries',

  // How It Works
  HOW_IT_WORKS_HEADLINE: 'GET STARTED IN MINUTES',
  HOW_IT_WORKS_SUBHEADLINE: 'Three simple steps to transform your workflow.',
  STEP_1_TITLE: 'SIGN UP',
  STEP_1_DESCRIPTION: 'Create your account in seconds. No credit card required.',
  STEP_2_TITLE: 'CONFIGURE',
  STEP_2_DESCRIPTION: 'Set up your preferences and connect your tools.',
  STEP_3_TITLE: 'LAUNCH',
  STEP_3_DESCRIPTION: 'Go live and start seeing results immediately.',

  // Pricing
  PRICING_HEADLINE: 'SIMPLE, TRANSPARENT PRICING',
  PRICING_SUBHEADLINE: 'No hidden fees. No surprises. Cancel anytime.',
  PRICE_TIER_1_NAME: 'STARTER',
  PRICE_TIER_1_PRICE: '$0',
  PRICE_TIER_1_PERIOD: '/month',
  PRICE_TIER_1_DESCRIPTION: 'Perfect for trying things out',
  PRICE_TIER_1_FEATURES: "'Up to 100 users', 'Basic analytics', 'Email support', '1 project'",
  PRICE_TIER_1_CTA: 'GET STARTED',
  PRICE_TIER_2_NAME: 'PRO',
  PRICE_TIER_2_PRICE: '$29',
  PRICE_TIER_2_PERIOD: '/month',
  PRICE_TIER_2_DESCRIPTION: 'Best for growing teams',
  PRICE_TIER_2_FEATURES: "'Unlimited users', 'Advanced analytics', 'Priority support', 'Unlimited projects', 'Custom integrations'",
  PRICE_TIER_2_CTA: 'START FREE TRIAL',
  PRICE_TIER_3_NAME: 'ENTERPRISE',
  PRICE_TIER_3_PRICE: 'Custom',
  PRICE_TIER_3_PERIOD: '',
  PRICE_TIER_3_DESCRIPTION: 'For large organizations',
  PRICE_TIER_3_FEATURES: "'Everything in Pro', 'Dedicated support', 'SLA guarantee', 'Custom contracts', 'On-premise option'",
  PRICE_TIER_3_CTA: 'CONTACT SALES',

  // FAQ
  FAQ_HEADLINE: 'FREQUENTLY ASKED QUESTIONS',
  FAQ_SUBHEADLINE: "Got questions? We've got answers.",
  FAQ_1_QUESTION: 'How does the free trial work?',
  FAQ_1_ANSWER: 'You get full access to all Pro features for 14 days. No credit card required.',
  FAQ_2_QUESTION: 'Can I cancel my subscription anytime?',
  FAQ_2_ANSWER: 'Yes, you can cancel your subscription at any time. Your access will continue until the end of your billing period.',
  FAQ_3_QUESTION: 'Do you offer refunds?',
  FAQ_3_ANSWER: "Yes, we offer a 30-day money-back guarantee. If you're not satisfied, contact us for a full refund.",
  FAQ_4_QUESTION: 'What payment methods do you accept?',
  FAQ_4_ANSWER: 'We accept all major credit cards (Visa, Mastercard, American Express) and PayPal.',
  FAQ_5_QUESTION: 'Is my data secure?',
  FAQ_5_ANSWER: 'Absolutely. We use industry-standard encryption and security practices.',

  // Final CTA
  FINAL_CTA_HEADLINE: 'READY TO GET STARTED?',
  FINAL_CTA_DESCRIPTION: 'Join thousands of users who are already transforming their workflow. Start your free trial today.',
  FINAL_CTA_PRIMARY_TEXT: 'START FREE TRIAL',
  FINAL_CTA_PRIMARY_URL: '/signup',
  FINAL_CTA_SECONDARY_TEXT: 'TALK TO SALES',
  FINAL_CTA_SECONDARY_URL: '/contact',
};

/**
 * Fill in the template with provided values
 */
export function fillTemplate(values: Record<string, string>): string {
  let result = landingPageTemplate;

  // Merge with defaults
  const mergedValues = { ...defaultValues, ...values };

  // Replace all placeholders
  for (const [key, value] of Object.entries(mergedValues)) {
    const placeholder = new RegExp(`\\{\\{${key}\\}\\}`, 'g');
    result = result.replace(placeholder, value);
  }

  return result;
}
