/**
 * AI App Landing Page Template
 * Generated by Fabrk Setup Wizard
 *
 * Customize this page with your own content using AI tools.
 * See FABRK-PROMPTS.md for ready-to-use prompts.
 */

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

// CUSTOMIZE: Update these values for your AI app
const APP_NAME = 'Your AI App';
const TAGLINE = 'Powered by the latest AI models';
const DESCRIPTION =
  'Build intelligent applications with cutting-edge AI. Chat, generate, analyze, and automate.';

// CUSTOMIZE: Update your AI capabilities
const CAPABILITIES = [
  {
    title: 'Natural Language Processing',
    description: 'Understand and generate human-like text with advanced language models.',
    icon: '💬',
  },
  {
    title: 'Code Generation',
    description: 'Generate, explain, and debug code in any programming language.',
    icon: '👨‍💻',
  },
  {
    title: 'Data Analysis',
    description: 'Extract insights from data with AI-powered analytics and visualization.',
    icon: '📈',
  },
  {
    title: 'Content Creation',
    description: 'Generate blog posts, marketing copy, and creative content at scale.',
    icon: '✍️',
  },
];

// CUSTOMIZE: Update your "How it works" steps
const HOW_IT_WORKS = [
  {
    step: '01',
    title: 'Input your request',
    description: 'Describe what you want in plain English. Our AI understands context and intent.',
  },
  {
    step: '02',
    title: 'AI processes your request',
    description:
      'Advanced models analyze your input and generate intelligent, contextual responses.',
  },
  {
    step: '03',
    title: 'Get instant results',
    description: 'Receive high-quality output in seconds. Iterate and refine as needed.',
  },
];

// CUSTOMIZE: Update use cases
const USE_CASES = [
  {
    title: 'Developers',
    description: 'Speed up coding with AI pair programming, code review, and documentation.',
    icon: '🛠️',
  },
  {
    title: 'Marketers',
    description: 'Create compelling copy, analyze campaigns, and personalize content at scale.',
    icon: '📢',
  },
  {
    title: 'Researchers',
    description: 'Summarize papers, extract insights, and accelerate literature reviews.',
    icon: '🔬',
  },
  {
    title: 'Creators',
    description: 'Generate ideas, outline content, and overcome creative blocks.',
    icon: '🎨',
  },
];

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      {/* Hero Section */}
      <section className="container mx-auto px-4 py-24 text-center">
        <Badge variant="outline" className="mb-4">
          [AI-POWERED]
        </Badge>
        <h1 className="mb-6 text-4xl font-bold tracking-tight sm:text-6xl">{APP_NAME}</h1>
        <p className="text-muted-foreground mx-auto mb-4 max-w-2xl text-xl">{TAGLINE}</p>
        <p className="text-muted-foreground mx-auto mb-8 max-w-xl">{DESCRIPTION}</p>
        <div className="flex flex-col justify-center gap-4 sm:flex-row">
          <Button size="lg" asChild>
            <Link href="/sign-up">&gt; TRY FOR FREE</Link>
          </Button>
          <Button size="lg" variant="outline" asChild>
            <Link href="/demo">&gt; SEE DEMO</Link>
          </Button>
        </div>
        <p className="text-muted-foreground mt-4 text-sm">No credit card required</p>
      </section>

      {/* Demo Preview Section */}
      <section className="bg-muted/50 py-24">
        <div className="container mx-auto px-4">
          <h2 className="mb-4 text-center text-3xl font-bold">SEE IT IN ACTION</h2>
          <p className="text-muted-foreground mx-auto mb-12 max-w-2xl text-center">
            Watch how AI transforms your workflow in seconds.
          </p>
          {/* Demo placeholder - replace with actual demo or video */}
          <div className="bg-card border-border mx-auto aspect-video max-w-4xl rounded-none border">
            <div className="flex h-full items-center justify-center">
              <div className="text-center">
                <p className="text-muted-foreground mb-2 text-4xl">▶</p>
                <p className="text-muted-foreground text-sm">[VIDEO DEMO PLACEHOLDER]</p>
                <p className="text-muted-foreground text-xs">Replace with your product demo</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* AI Capabilities */}
      <section className="py-24">
        <div className="container mx-auto px-4">
          <h2 className="mb-4 text-center text-3xl font-bold">AI CAPABILITIES</h2>
          <p className="text-muted-foreground mx-auto mb-12 max-w-2xl text-center">
            Powerful AI features to supercharge your productivity.
          </p>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
            {CAPABILITIES.map((capability) => (
              <Card key={capability.title}>
                <CardHeader>
                  <div className="mb-2 text-4xl">{capability.icon}</div>
                  <CardTitle className="text-lg">{capability.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription>{capability.description}</CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="bg-muted/50 py-24">
        <div className="container mx-auto px-4">
          <h2 className="mb-4 text-center text-3xl font-bold">HOW IT WORKS</h2>
          <p className="text-muted-foreground mx-auto mb-12 max-w-2xl text-center">
            Get started in three simple steps.
          </p>
          <div className="mx-auto grid max-w-4xl gap-8 md:grid-cols-3">
            {HOW_IT_WORKS.map((step) => (
              <div key={step.step} className="text-center">
                <div className="text-primary mb-4 text-5xl font-bold">{step.step}</div>
                <h3 className="mb-2 text-xl font-semibold">{step.title}</h3>
                <p className="text-muted-foreground">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Use Cases */}
      <section className="py-24">
        <div className="container mx-auto px-4">
          <h2 className="mb-4 text-center text-3xl font-bold">WHO IT&apos;S FOR</h2>
          <p className="text-muted-foreground mx-auto mb-12 max-w-2xl text-center">
            Built for professionals who want to work smarter.
          </p>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
            {USE_CASES.map((useCase) => (
              <Card key={useCase.title}>
                <CardHeader>
                  <div className="mb-2 text-4xl">{useCase.icon}</div>
                  <CardTitle className="text-lg">{useCase.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription>{useCase.description}</CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Preview */}
      <section className="bg-muted/50 py-24">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-3xl font-bold">SIMPLE PRICING</h2>
          <p className="text-muted-foreground mx-auto mb-8 max-w-xl">
            Start free, upgrade when you need more.
          </p>
          <Card className="mx-auto max-w-md">
            <CardHeader>
              <CardTitle>Free Tier</CardTitle>
              <CardDescription>Perfect for getting started</CardDescription>
              <div className="mt-4">
                <span className="text-4xl font-bold">$0</span>
                <span className="text-muted-foreground">/month</span>
              </div>
            </CardHeader>
            <CardContent>
              <ul className="mb-6 space-y-2 text-left">
                <li className="flex items-center gap-2">
                  <span className="text-primary">+</span> 100 AI requests/month
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-primary">+</span> Basic models
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-primary">+</span> Community support
                </li>
              </ul>
              <Button className="w-full" asChild>
                <Link href="/sign-up">&gt; START FREE</Link>
              </Button>
            </CardContent>
          </Card>
          <p className="text-muted-foreground mt-6 text-sm">
            Need more?{' '}
            <Link href="/pricing" className="text-primary underline">
              View all plans
            </Link>
          </p>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-3xl font-bold">READY TO BUILD WITH AI?</h2>
          <p className="text-muted-foreground mx-auto mb-8 max-w-xl">
            Join thousands of users leveraging AI to work smarter.
          </p>
          <div className="flex flex-col justify-center gap-4 sm:flex-row">
            <Button size="lg" asChild>
              <Link href="/sign-up">&gt; GET STARTED FREE</Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="/contact">&gt; TALK TO SALES</Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
