/**
 * Marketplace Landing Page - Amazon/Etsy Style
 * Generated by Fabrk Setup Wizard
 *
 * Best for: Physical products, digital goods, multi-vendor marketplaces
 * See FABRK-PROMPTS.md for ready-to-use prompts.
 */

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';

// CUSTOMIZE: Update these values for your marketplace
const MARKETPLACE_NAME = 'Your Marketplace';
const TAGLINE = 'Find everything you need in one place';
const DESCRIPTION = 'Shop from thousands of sellers. Best prices, fast shipping, secure payments.';

// CUSTOMIZE: Update categories
const CATEGORIES = [
  { name: 'Electronics', icon: '📱', count: '2,500+' },
  { name: 'Fashion', icon: '👗', count: '5,000+' },
  { name: 'Home & Garden', icon: '🏠', count: '3,200+' },
  { name: 'Sports', icon: '⚽', count: '1,800+' },
  { name: 'Books', icon: '📚', count: '10,000+' },
  { name: 'Toys', icon: '🎮', count: '2,100+' },
];

// CUSTOMIZE: Update featured products
const FEATURED_PRODUCTS = [
  {
    name: 'Product Name',
    price: '$99.00',
    originalPrice: '$149.00',
    rating: 4.8,
    reviews: 234,
    seller: 'Top Seller',
    badge: 'BESTSELLER',
  },
  {
    name: 'Another Product',
    price: '$49.00',
    originalPrice: null,
    rating: 4.5,
    reviews: 89,
    seller: 'Quality Goods',
    badge: null,
  },
  {
    name: 'Premium Item',
    price: '$199.00',
    originalPrice: '$299.00',
    rating: 4.9,
    reviews: 567,
    seller: 'Premium Store',
    badge: 'DEAL',
  },
  {
    name: 'Popular Choice',
    price: '$29.00',
    originalPrice: null,
    rating: 4.3,
    reviews: 123,
    seller: 'Value Shop',
    badge: null,
  },
];

// CUSTOMIZE: Update trust badges
const TRUST_BADGES = [
  { text: 'Secure Payments', icon: '🔒' },
  { text: 'Fast Shipping', icon: '🚚' },
  { text: 'Easy Returns', icon: '↩️' },
  { text: 'Best Prices', icon: '💰' },
];

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      {/* Hero with Search */}
      <section className="bg-primary text-primary-foreground py-16">
        <div className="container mx-auto px-4">
          <h1 className="mb-4 text-center text-4xl font-bold sm:text-5xl">{MARKETPLACE_NAME}</h1>
          <p className="mx-auto mb-8 max-w-2xl text-center text-lg opacity-90">{TAGLINE}</p>

          {/* Search Bar */}
          <div className="mx-auto flex max-w-2xl gap-2">
            <Input
              type="search"
              placeholder="Search for products..."
              className="bg-background text-foreground flex-1 rounded-none"
            />
            <Button variant="secondary" className="rounded-none">
              &gt; SEARCH
            </Button>
          </div>
        </div>
      </section>

      {/* Category Grid */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <h2 className="mb-8 text-center text-2xl font-bold">SHOP BY CATEGORY</h2>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">
            {CATEGORIES.map((category) => (
              <Link href={`/category/${category.name.toLowerCase()}`} key={category.name}>
                <Card className="hover:border-primary cursor-pointer text-center transition-colors">
                  <CardContent className="pt-6">
                    <div className="mb-2 text-4xl">{category.icon}</div>
                    <h3 className="font-semibold">{category.name}</h3>
                    <p className="text-muted-foreground text-sm">{category.count} items</p>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Featured Products */}
      <section className="bg-muted/50 py-16">
        <div className="container mx-auto px-4">
          <div className="mb-8 flex items-center justify-between">
            <h2 className="text-2xl font-bold">FEATURED PRODUCTS</h2>
            <Link href="/products" className="text-primary hover:underline">
              View all →
            </Link>
          </div>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {FEATURED_PRODUCTS.map((product, index) => (
              <Card key={index} className="overflow-hidden">
                {/* Product Image Placeholder */}
                <div className="bg-muted flex aspect-square items-center justify-center">
                  <span className="text-muted-foreground text-sm">[PRODUCT IMAGE]</span>
                </div>
                <CardContent className="pt-4">
                  {product.badge && (
                    <Badge variant="destructive" className="mb-2">
                      {product.badge}
                    </Badge>
                  )}
                  <h3 className="mb-1 font-semibold">{product.name}</h3>
                  <div className="mb-2 flex items-center gap-2">
                    <span className="text-lg font-bold">{product.price}</span>
                    {product.originalPrice && (
                      <span className="text-muted-foreground text-sm line-through">
                        {product.originalPrice}
                      </span>
                    )}
                  </div>
                  <div className="text-muted-foreground mb-2 text-sm">
                    ⭐ {product.rating} ({product.reviews} reviews)
                  </div>
                  <p className="text-muted-foreground text-xs">Sold by {product.seller}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Trust Badges */}
      <section className="py-12">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
            {TRUST_BADGES.map((badge) => (
              <div key={badge.text} className="text-center">
                <div className="mb-2 text-3xl">{badge.icon}</div>
                <p className="text-muted-foreground text-sm font-medium">{badge.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Seller CTA */}
      <section className="bg-muted/50 py-16">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-2xl font-bold">BECOME A SELLER</h2>
          <p className="text-muted-foreground mx-auto mb-6 max-w-xl">
            Join thousands of sellers on {MARKETPLACE_NAME}. Reach millions of customers and grow
            your business.
          </p>
          <div className="flex flex-col justify-center gap-4 sm:flex-row">
            <Button size="lg" asChild>
              <Link href="/sell">&gt; START SELLING</Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="/seller-guide">&gt; LEARN MORE</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Newsletter */}
      <section className="py-16">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-2xl font-bold">STAY UPDATED</h2>
          <p className="text-muted-foreground mx-auto mb-6 max-w-md">
            Get the latest deals and new arrivals delivered to your inbox.
          </p>
          <div className="mx-auto flex max-w-md gap-2">
            <Input type="email" placeholder="Enter your email" className="flex-1 rounded-none" />
            <Button className="rounded-none">&gt; SUBSCRIBE</Button>
          </div>
        </div>
      </section>
    </div>
  );
}
