/**
 * Marketplace Landing Page - Airbnb/Zillow Style
 * Generated by Fabrk Setup Wizard
 *
 * Best for: Rentals, services, experiences, listings with images
 * See FABRK-PROMPTS.md for ready-to-use prompts.
 */

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';

// CUSTOMIZE: Update these values for your marketplace
const MARKETPLACE_NAME = 'Your Marketplace';
const TAGLINE = 'Find unique places to stay';
const DESCRIPTION = 'Book accommodations, experiences, and more from local hosts around the world.';

// CUSTOMIZE: Update popular destinations/categories
const POPULAR_DESTINATIONS = [
  { name: 'New York', image: '🏙️', listings: '1,200+' },
  { name: 'Los Angeles', image: '🌴', listings: '900+' },
  { name: 'Miami', image: '🏖️', listings: '750+' },
  { name: 'Chicago', image: '🌃', listings: '600+' },
];

// CUSTOMIZE: Update featured listings
const FEATURED_LISTINGS = [
  {
    title: 'Modern Downtown Loft',
    location: 'New York, NY',
    price: '$150',
    period: '/night',
    rating: 4.9,
    reviews: 128,
    type: 'Entire place',
    superhost: true,
  },
  {
    title: 'Cozy Beach House',
    location: 'Miami, FL',
    price: '$200',
    period: '/night',
    rating: 4.8,
    reviews: 95,
    type: 'Entire place',
    superhost: false,
  },
  {
    title: 'Mountain Cabin Retreat',
    location: 'Denver, CO',
    price: '$125',
    period: '/night',
    rating: 4.95,
    reviews: 234,
    type: 'Entire place',
    superhost: true,
  },
  {
    title: 'Urban Studio',
    location: 'San Francisco, CA',
    price: '$95',
    period: '/night',
    rating: 4.7,
    reviews: 67,
    type: 'Private room',
    superhost: false,
  },
];

// CUSTOMIZE: Update property types
const PROPERTY_TYPES = [
  { name: 'Houses', icon: '🏠', count: 5000 },
  { name: 'Apartments', icon: '🏢', count: 8000 },
  { name: 'Cabins', icon: '🏕️', count: 1200 },
  { name: 'Unique stays', icon: '✨', count: 500 },
];

// CUSTOMIZE: Update experience types
const EXPERIENCES = [
  { name: 'Food & Drink', icon: '🍷', description: 'Local culinary experiences' },
  { name: 'Adventure', icon: '🏄', description: 'Outdoor activities' },
  { name: 'Art & Culture', icon: '🎨', description: 'Creative workshops' },
  { name: 'Wellness', icon: '🧘', description: 'Relaxation retreats' },
];

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      {/* Hero with Search */}
      <section className="relative py-24">
        {/* Background placeholder */}
        <div className="bg-muted absolute inset-0 -z-10">
          <div className="flex h-full items-center justify-center">
            <span className="text-muted-foreground">[HERO BACKGROUND IMAGE]</span>
          </div>
        </div>

        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="mb-4 text-4xl font-bold sm:text-6xl">{TAGLINE}</h1>
            <p className="text-muted-foreground mb-8 text-xl">{DESCRIPTION}</p>
          </div>

          {/* Search Box */}
          <Card className="mx-auto max-w-4xl">
            <CardContent className="p-4">
              <div className="grid gap-4 md:grid-cols-4">
                <div>
                  <label className="text-muted-foreground mb-1 block text-sm">Where</label>
                  <Input placeholder="Search destinations" className="rounded-none" />
                </div>
                <div>
                  <label className="text-muted-foreground mb-1 block text-sm">Check in</label>
                  <Input type="date" className="rounded-none" />
                </div>
                <div>
                  <label className="text-muted-foreground mb-1 block text-sm">Check out</label>
                  <Input type="date" className="rounded-none" />
                </div>
                <div className="flex items-end">
                  <Button className="w-full rounded-none">&gt; SEARCH</Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Featured Listings */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <h2 className="mb-8 text-2xl font-bold">FEATURED LISTINGS</h2>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {FEATURED_LISTINGS.map((listing, index) => (
              <Link href="/listing/example" key={index}>
                <Card className="hover:border-primary cursor-pointer overflow-hidden transition-colors">
                  {/* Listing Image Placeholder */}
                  <div className="bg-muted relative aspect-[4/3]">
                    <div className="flex h-full items-center justify-center">
                      <span className="text-muted-foreground text-sm">[LISTING IMAGE]</span>
                    </div>
                    {listing.superhost && (
                      <Badge className="absolute top-2 left-2" variant="secondary">
                        SUPERHOST
                      </Badge>
                    )}
                  </div>
                  <CardContent className="pt-4">
                    <div className="mb-1 flex items-center justify-between">
                      <span className="text-muted-foreground text-sm">{listing.location}</span>
                      <span className="text-sm">
                        ⭐ {listing.rating} ({listing.reviews})
                      </span>
                    </div>
                    <h3 className="mb-1 font-semibold">{listing.title}</h3>
                    <p className="text-muted-foreground mb-2 text-sm">{listing.type}</p>
                    <div>
                      <span className="font-bold">{listing.price}</span>
                      <span className="text-muted-foreground">{listing.period}</span>
                    </div>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Popular Destinations */}
      <section className="bg-muted/50 py-16">
        <div className="container mx-auto px-4">
          <h2 className="mb-8 text-2xl font-bold">POPULAR DESTINATIONS</h2>
          <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
            {POPULAR_DESTINATIONS.map((destination) => (
              <Link href={`/search?location=${destination.name}`} key={destination.name}>
                <Card className="hover:border-primary cursor-pointer overflow-hidden transition-colors">
                  {/* Destination Image Placeholder */}
                  <div className="bg-muted flex aspect-[3/2] items-center justify-center">
                    <span className="text-6xl">{destination.image}</span>
                  </div>
                  <CardContent className="pt-4">
                    <h3 className="font-semibold">{destination.name}</h3>
                    <p className="text-muted-foreground text-sm">{destination.listings} listings</p>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Property Types */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <h2 className="mb-8 text-2xl font-bold">BROWSE BY TYPE</h2>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
            {PROPERTY_TYPES.map((type) => (
              <Link href={`/search?type=${type.name.toLowerCase()}`} key={type.name}>
                <Card className="hover:border-primary cursor-pointer text-center transition-colors">
                  <CardContent className="pt-6">
                    <div className="mb-2 text-4xl">{type.icon}</div>
                    <h3 className="font-semibold">{type.name}</h3>
                    <p className="text-muted-foreground text-sm">
                      {type.count.toLocaleString()} listings
                    </p>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Experiences */}
      <section className="bg-muted/50 py-16">
        <div className="container mx-auto px-4">
          <h2 className="mb-8 text-2xl font-bold">EXPERIENCES</h2>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {EXPERIENCES.map((experience) => (
              <Link href={`/experiences/${experience.name.toLowerCase()}`} key={experience.name}>
                <Card className="hover:border-primary cursor-pointer transition-colors">
                  <CardContent className="pt-6">
                    <div className="mb-2 text-4xl">{experience.icon}</div>
                    <h3 className="font-semibold">{experience.name}</h3>
                    <p className="text-muted-foreground text-sm">{experience.description}</p>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Host CTA */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <Card className="overflow-hidden">
            <div className="grid md:grid-cols-2">
              {/* Image placeholder */}
              <div className="bg-muted flex items-center justify-center p-12">
                <span className="text-muted-foreground">[HOST IMAGE]</span>
              </div>
              <div className="flex flex-col justify-center p-8">
                <h2 className="mb-4 text-3xl font-bold">BECOME A HOST</h2>
                <p className="text-muted-foreground mb-6">
                  Earn extra income by sharing your space with travelers from around the world.
                  You&apos;re in control of your availability, prices, and house rules.
                </p>
                <div className="space-y-2 text-sm">
                  <p className="flex items-center gap-2">
                    <span className="text-primary">+</span> Average hosts earn $9,600/year
                  </p>
                  <p className="flex items-center gap-2">
                    <span className="text-primary">+</span> 24/7 host support
                  </p>
                  <p className="flex items-center gap-2">
                    <span className="text-primary">+</span> $1M host protection insurance
                  </p>
                </div>
                <Button className="mt-6 w-fit" size="lg" asChild>
                  <Link href="/host">&gt; START HOSTING</Link>
                </Button>
              </div>
            </div>
          </Card>
        </div>
      </section>
    </div>
  );
}
