/**
 * Marketplace Landing Page - Gumroad/Minimal Style
 * Generated by Fabrk Setup Wizard
 *
 * Best for: Digital creators, courses, ebooks, templates, design assets
 * See FABRK-PROMPTS.md for ready-to-use prompts.
 */

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

// CUSTOMIZE: Update these values for your creator marketplace
const MARKETPLACE_NAME = 'Your Marketplace';
const TAGLINE = 'Digital products by creators, for creators';
const DESCRIPTION = 'Discover and sell digital products. No middleman, just pure creativity.';

// CUSTOMIZE: Update featured creators
const FEATURED_CREATORS = [
  {
    name: 'Alex Design',
    handle: '@alexdesign',
    products: 12,
    sales: '2.5k',
    category: 'Design',
  },
  {
    name: 'Code Academy',
    handle: '@codeacademy',
    products: 8,
    sales: '5k',
    category: 'Development',
  },
  {
    name: 'Sarah Writes',
    handle: '@sarahwrites',
    products: 15,
    sales: '3.2k',
    category: 'Writing',
  },
];

// CUSTOMIZE: Update featured products
const FEATURED_PRODUCTS = [
  {
    title: 'Complete Design System',
    creator: 'Alex Design',
    price: '$49',
    originalPrice: '$99',
    category: 'Design',
    sales: '500+',
    rating: 4.9,
  },
  {
    title: 'React Component Library',
    creator: 'Code Academy',
    price: '$79',
    originalPrice: null,
    category: 'Development',
    sales: '1.2k',
    rating: 4.8,
  },
  {
    title: 'Copywriting Templates',
    creator: 'Sarah Writes',
    price: '$29',
    originalPrice: null,
    category: 'Writing',
    sales: '800+',
    rating: 4.7,
  },
  {
    title: 'Icon Pack Bundle',
    creator: 'Alex Design',
    price: '$19',
    originalPrice: '$39',
    category: 'Design',
    sales: '2k+',
    rating: 5.0,
  },
];

// CUSTOMIZE: Update categories
const CATEGORIES = [
  { name: 'Design', count: '1,200+', icon: '🎨' },
  { name: 'Development', count: '800+', icon: '💻' },
  { name: 'Writing', count: '500+', icon: '✍️' },
  { name: 'Business', count: '400+', icon: '📊' },
  { name: 'Education', count: '600+', icon: '📚' },
  { name: 'Music', count: '300+', icon: '🎵' },
];

// CUSTOMIZE: Update why sell section
const WHY_SELL = [
  {
    title: 'Keep 90% of sales',
    description: "We only take a small fee. You keep the majority of what you earn.",
    icon: '💰',
  },
  {
    title: 'Instant payouts',
    description: 'Get paid directly to your bank account. No waiting periods.',
    icon: '⚡',
  },
  {
    title: 'Built-in audience',
    description: 'Access millions of buyers actively looking for digital products.',
    icon: '🌍',
  },
  {
    title: 'Simple tools',
    description: 'Upload, price, and sell. No technical skills required.',
    icon: '🛠️',
  },
];

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      {/* Hero - Clean and Minimal */}
      <section className="py-24">
        <div className="container mx-auto px-4 text-center">
          <Badge variant="outline" className="mb-4">
            [BY CREATORS, FOR CREATORS]
          </Badge>
          <h1 className="mb-6 text-4xl font-bold tracking-tight sm:text-6xl">{TAGLINE}</h1>
          <p className="text-muted-foreground mx-auto mb-8 max-w-xl text-xl">{DESCRIPTION}</p>
          <div className="flex flex-col justify-center gap-4 sm:flex-row">
            <Button size="lg" asChild>
              <Link href="/browse">&gt; BROWSE PRODUCTS</Link>
            </Button>
            <Button size="lg" variant="outline" asChild>
              <Link href="/sell">&gt; START SELLING</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Featured Products - Simple Grid */}
      <section className="bg-muted/50 py-16">
        <div className="container mx-auto px-4">
          <div className="mb-8 flex items-center justify-between">
            <h2 className="text-2xl font-bold">TRENDING NOW</h2>
            <Link href="/browse" className="text-primary hover:underline">
              See all →
            </Link>
          </div>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {FEATURED_PRODUCTS.map((product, index) => (
              <Link href="/product/example" key={index}>
                <Card className="hover:border-primary cursor-pointer overflow-hidden transition-colors">
                  {/* Product Preview */}
                  <div className="bg-muted flex aspect-square items-center justify-center">
                    <span className="text-muted-foreground text-sm">[PRODUCT PREVIEW]</span>
                  </div>
                  <CardContent className="pt-4">
                    <Badge variant="secondary" className="mb-2">
                      {product.category}
                    </Badge>
                    <h3 className="mb-1 font-semibold">{product.title}</h3>
                    <p className="text-muted-foreground mb-2 text-sm">by {product.creator}</p>
                    <div className="mb-2 flex items-center gap-2">
                      <span className="text-lg font-bold">{product.price}</span>
                      {product.originalPrice && (
                        <span className="text-muted-foreground text-sm line-through">
                          {product.originalPrice}
                        </span>
                      )}
                    </div>
                    <div className="text-muted-foreground flex items-center gap-2 text-sm">
                      <span>⭐ {product.rating}</span>
                      <span>•</span>
                      <span>{product.sales} sales</span>
                    </div>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Categories - Minimal */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <h2 className="mb-8 text-center text-2xl font-bold">BROWSE BY CATEGORY</h2>
          <div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6">
            {CATEGORIES.map((category) => (
              <Link href={`/category/${category.name.toLowerCase()}`} key={category.name}>
                <Card className="hover:border-primary cursor-pointer text-center transition-colors">
                  <CardContent className="py-6">
                    <div className="mb-2 text-3xl">{category.icon}</div>
                    <h3 className="mb-1 font-semibold">{category.name}</h3>
                    <p className="text-muted-foreground text-sm">{category.count}</p>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Featured Creators */}
      <section className="bg-muted/50 py-16">
        <div className="container mx-auto px-4">
          <h2 className="mb-8 text-center text-2xl font-bold">TOP CREATORS</h2>
          <div className="mx-auto grid max-w-4xl gap-6 md:grid-cols-3">
            {FEATURED_CREATORS.map((creator) => (
              <Link href={`/@${creator.handle.replace('@', '')}`} key={creator.handle}>
                <Card className="hover:border-primary cursor-pointer transition-colors">
                  <CardContent className="pt-6 text-center">
                    {/* Avatar placeholder */}
                    <div className="bg-muted mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full">
                      <span className="text-muted-foreground text-xs">[AVATAR]</span>
                    </div>
                    <h3 className="font-semibold">{creator.name}</h3>
                    <p className="text-muted-foreground mb-2 text-sm">{creator.handle}</p>
                    <Badge variant="outline" className="mb-3">
                      {creator.category}
                    </Badge>
                    <div className="text-muted-foreground flex justify-center gap-4 text-sm">
                      <span>{creator.products} products</span>
                      <span>{creator.sales} sales</span>
                    </div>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Why Sell */}
      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="mb-4 text-3xl font-bold">WHY SELL WITH US</h2>
            <p className="text-muted-foreground mb-12">
              Join thousands of creators earning from their digital products.
            </p>
          </div>
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            {WHY_SELL.map((item) => (
              <div key={item.title} className="text-center">
                <div className="mb-4 text-4xl">{item.icon}</div>
                <h3 className="mb-2 font-semibold">{item.title}</h3>
                <p className="text-muted-foreground text-sm">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Simple CTA */}
      <section className="bg-primary text-primary-foreground py-16">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-3xl font-bold">READY TO START?</h2>
          <p className="mx-auto mb-8 max-w-md opacity-90">
            Create your store in minutes. No monthly fees, no hidden costs.
          </p>
          <Button size="lg" variant="secondary" asChild>
            <Link href="/sell">&gt; CREATE YOUR STORE</Link>
          </Button>
          <p className="mt-4 text-sm opacity-75">Free to start • No credit card required</p>
        </div>
      </section>

      {/* Footer Stats */}
      <section className="py-12">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-3 gap-4 text-center">
            <div>
              <p className="text-3xl font-bold">50K+</p>
              <p className="text-muted-foreground text-sm">Creators</p>
            </div>
            <div>
              <p className="text-3xl font-bold">$10M+</p>
              <p className="text-muted-foreground text-sm">Paid to creators</p>
            </div>
            <div>
              <p className="text-3xl font-bold">1M+</p>
              <p className="text-muted-foreground text-sm">Products sold</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
