/**
 * SaaS Landing Page Template
 * Generated by Fabrk Setup Wizard
 *
 * Customize this page with your own content using AI tools.
 * See FABRK-PROMPTS.md for ready-to-use prompts.
 */

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

// CUSTOMIZE: Update these values for your app
const APP_NAME = 'Your App';
const TAGLINE = 'Ship faster with a production-ready stack';
const DESCRIPTION = 'Everything you need to build, launch, and scale your SaaS product.';

// CUSTOMIZE: Update your features
const FEATURES = [
  {
    title: 'Authentication',
    description: 'Secure user authentication with NextAuth.js. Email, OAuth, magic links.',
    icon: '🔐',
  },
  {
    title: 'Payments',
    description: 'Stripe integration for subscriptions and one-time payments.',
    icon: '💳',
  },
  {
    title: 'Database',
    description: 'PostgreSQL with Prisma ORM. Type-safe queries and migrations.',
    icon: '🗄️',
  },
  {
    title: 'Email',
    description: 'Transactional emails with Resend. Beautiful templates included.',
    icon: '📧',
  },
  {
    title: 'Analytics',
    description: 'PostHog integration for product analytics and feature flags.',
    icon: '📊',
  },
  {
    title: 'Dashboard',
    description: 'Admin dashboard with user management and billing portal.',
    icon: '📱',
  },
];

// CUSTOMIZE: Update your pricing tiers
const PRICING = [
  {
    name: 'Starter',
    price: '$0',
    period: '/month',
    description: 'Perfect for side projects',
    features: ['Up to 100 users', 'Basic analytics', 'Email support'],
    cta: 'Get Started',
    popular: false,
  },
  {
    name: 'Pro',
    price: '$29',
    period: '/month',
    description: 'For growing businesses',
    features: ['Unlimited users', 'Advanced analytics', 'Priority support', 'API access'],
    cta: 'Start Free Trial',
    popular: true,
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    period: '',
    description: 'For large organizations',
    features: ['Custom limits', 'Dedicated support', 'SLA guarantee', 'Custom integrations'],
    cta: 'Contact Sales',
    popular: false,
  },
];

// CUSTOMIZE: Update testimonials
const TESTIMONIALS = [
  {
    quote: 'This saved us weeks of development time. Highly recommended!',
    author: 'Jane Doe',
    role: 'CTO, TechStartup',
  },
  {
    quote: 'The best boilerplate I have ever used. Clean code and great documentation.',
    author: 'John Smith',
    role: 'Founder, AppCo',
  },
];

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      {/* Hero Section */}
      <section className="container mx-auto px-4 py-24 text-center">
        <Badge variant="outline" className="mb-4">
          [NOW AVAILABLE]
        </Badge>
        <h1 className="mb-6 text-4xl font-bold tracking-tight sm:text-6xl">{APP_NAME}</h1>
        <p className="text-muted-foreground mx-auto mb-8 max-w-2xl text-xl">{TAGLINE}</p>
        <p className="text-muted-foreground mx-auto mb-8 max-w-xl">{DESCRIPTION}</p>
        <div className="flex flex-col justify-center gap-4 sm:flex-row">
          <Button size="lg" asChild>
            <Link href="/sign-up">&gt; GET STARTED</Link>
          </Button>
          <Button size="lg" variant="outline" asChild>
            <Link href="/docs">&gt; VIEW DOCS</Link>
          </Button>
        </div>
      </section>

      {/* Features Section */}
      <section className="bg-muted/50 py-24">
        <div className="container mx-auto px-4">
          <h2 className="mb-4 text-center text-3xl font-bold">FEATURES</h2>
          <p className="text-muted-foreground mx-auto mb-12 max-w-2xl text-center">
            Everything you need to build a production-ready SaaS.
          </p>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {FEATURES.map((feature) => (
              <Card key={feature.title}>
                <CardHeader>
                  <div className="mb-2 text-4xl">{feature.icon}</div>
                  <CardTitle>{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription>{feature.description}</CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="py-24">
        <div className="container mx-auto px-4">
          <h2 className="mb-4 text-center text-3xl font-bold">PRICING</h2>
          <p className="text-muted-foreground mx-auto mb-12 max-w-2xl text-center">
            Simple, transparent pricing. No hidden fees.
          </p>
          <div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-3">
            {PRICING.map((tier) => (
              <Card key={tier.name} className={tier.popular ? 'border-primary' : ''}>
                <CardHeader>
                  {tier.popular && (
                    <Badge className="mb-2 w-fit" variant="default">
                      MOST POPULAR
                    </Badge>
                  )}
                  <CardTitle>{tier.name}</CardTitle>
                  <CardDescription>{tier.description}</CardDescription>
                  <div className="mt-4">
                    <span className="text-4xl font-bold">{tier.price}</span>
                    <span className="text-muted-foreground">{tier.period}</span>
                  </div>
                </CardHeader>
                <CardContent>
                  <ul className="mb-6 space-y-2">
                    {tier.features.map((feature) => (
                      <li key={feature} className="flex items-center gap-2">
                        <span className="text-primary">+</span> {feature}
                      </li>
                    ))}
                  </ul>
                  <Button className="w-full" variant={tier.popular ? 'default' : 'outline'} asChild>
                    <Link href="/sign-up">&gt; {tier.cta.toUpperCase()}</Link>
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="bg-muted/50 py-24">
        <div className="container mx-auto px-4">
          <h2 className="mb-12 text-center text-3xl font-bold">WHAT CUSTOMERS SAY</h2>
          <div className="mx-auto grid max-w-4xl gap-8 md:grid-cols-2">
            {TESTIMONIALS.map((testimonial) => (
              <Card key={testimonial.author}>
                <CardContent className="pt-6">
                  <p className="mb-4 text-lg italic">&quot;{testimonial.quote}&quot;</p>
                  <div>
                    <p className="font-semibold">{testimonial.author}</p>
                    <p className="text-muted-foreground text-sm">{testimonial.role}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-3xl font-bold">READY TO GET STARTED?</h2>
          <p className="text-muted-foreground mx-auto mb-8 max-w-xl">
            Join thousands of developers building with {APP_NAME}.
          </p>
          <Button size="lg" asChild>
            <Link href="/sign-up">&gt; START BUILDING TODAY</Link>
          </Button>
        </div>
      </section>
    </div>
  );
}
